<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-11T10:08:04 IST" name="Default suite" finished-at="2024-04-11T10:09:38 IST" duration-ms="93902">
    <groups>
    </groups>
    <test started-at="2024-04-11T10:08:04 IST" name="Default test" finished-at="2024-04-11T10:09:38 IST" duration-ms="93902">
      <class name="Masters.Batch">
        <test-method is-config="true" signature="TEEMSLOGIN()[pri:0, instance:Masters.Batch@5fbdfdcf]" started-at="2024-04-11T10:08:04 IST" name="TEEMSLOGIN" finished-at="2024-04-11T10:08:46 IST" duration-ms="42444" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TEEMSLOGIN -->
        <test-method signature="ADD_Batch()[pri:0, instance:Masters.Batch@5fbdfdcf]" started-at="2024-04-11T10:08:46 IST" name="ADD_Batch" finished-at="2024-04-11T10:09:38 IST" duration-ms="51057" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Test failed because the popup message did not contain 'Successfully'.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Test failed because the popup message did not contain 'Successfully'.
at Masters.Batch.ADD_Batch(Batch.java:207)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ADD_Batch -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Masters.Batch@5fbdfdcf]" started-at="2024-04-11T10:09:38 IST" name="teardown" finished-at="2024-04-11T10:09:38 IST" duration-ms="348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Masters.Batch -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
